/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testEqual() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertTrue(App.sumOfElementsIsEqual(array, 0,1,3));
    }

    @Test
    public void testNotEqual() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertFalse(App.sumOfElementsIsEqual(array, 0,1,5));
    }

    @Test
    public void testArrayOutOfBound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(7, 8, 3, 4));
       assertFalse(App.sumOfElementsIsEqual(array, 10,1,3));
    }

    @Test
    public void testSameIndex() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertTrue(App.sumOfElementsIsEqual(array, 0,0,2));
    }

    @Test
    public void testNull() {
       assertFalse(App.sumOfElementsIsEqual(null, 5,5,3));
    }
}
